/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LoginUrlResponse {
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "redirect_uri")]
    pub redirect_uri: String,
    #[serde(rename = "response_type")]
    pub response_type: String,
    #[serde(rename = "scope")]
    pub scope: String,
    #[serde(rename = "state")]
    pub state: String,
}

impl LoginUrlResponse {
    pub fn new(client_id: String, redirect_uri: String, response_type: String, scope: String, state: String) -> LoginUrlResponse {
        LoginUrlResponse {
            client_id,
            redirect_uri,
            response_type,
            scope,
            state,
        }
    }
}


