/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LoginUrlRequest {
    #[serde(rename = "callback_url")]
    pub callback_url: String,
}

impl LoginUrlRequest {
    pub fn new(callback_url: String) -> LoginUrlRequest {
        LoginUrlRequest {
            callback_url,
        }
    }
}


